### ISSUE TITLE
kinfitr models output no files

### ISSUE THREAD

**Issue by evieneylon98** [bilgelm/dynamicpet#103]
Hello! Thank you for sharing this tool.

I am trying to run the kinfitr implementations, but having some trouble.

I've followed the instructions on the site and successfully loaded the kinfitr extra. I've also double checked the package is installed in R.
I am using ubuntu 22.04, python 3.11 and R 4.1.2, and the latest project commit.

I tried the following command:
kineticmodel sub-000101_ses-baseline_pet.nii.gz --model kinfitr.SRTM --refmask refmask_inPET.nii.gz --outputdir output --json sub-000101_ses-baseline_pet.json --fwhm 5

The command runs for about 15 seconds and then stops without error. However, when I check the output directory, there are no files. his happens with both available kinfitr models. This does not happen when I use the other models (e.g. SRTMZhou2003), where files are outputted correctly, so I can only assume there is a problem somewhere with kinfitr.

It is difficult to know without a log file but how can I tell if there is an issue with my own setup of the repository, or perhaps a bug somewhere in the code itself?

I'd greatly appreciate your insights on this! Thank you

**Comment by bilgelm** [comment]
Hi @evieneylon98 , thanks giving the dynamicpet tool a try and for opening this issue. In the command line interface, I inadvertenly neglected to call the `fit` function for the kinfitr models. I just fixed the issue, so it should work now. These models will probably take quite some time to finish running, so I'd recommend trying these out with small images, at least to start.
